### PR TITLE
Define the means by which we promote Final Specifications #302

### PR DESCRIPTION
**Pull request by chrisguindon**
Signed-off-by: Christopher Guindon <chris.guindon@eclipse-foundation.org>

### CODE REVIEW

**Comment by ggam** [comment]
The only problem I see with this approach is that you need to manually
rebuild this repository to get the changes.

**Comment by chrisguindon** [comment]
> The only problem I see with this approach is that you need to manually rebuild this repository to get the changes. 

Correct! This is something that I brought up with @waynebeaton before working on this.

I will investigate if there is away to trigger a build on jakarta.ee each time a commit is done on the specifications repo.

An alternative, is to configure a cron job in travis-ci to rebuild the site every day. It will be important to run some tests on the specification repo to make sure that the content can be successfully compiled by hugo.

**Comment by chrisguindon** [comment]
It seems possible to programmatically trigger a job:

- https://docs.travis-ci.com/user/triggering-builds/
- https://github.com/plume-lib/trigger-travis/

**Comment by waynebeaton** [comment]
What is our status? Can we roll this out?

When we make updates to the /specifications repository, how do we roll out the change?

**Comment by chrisguindon** [comment]
@waynebeaton We can merge it at anytime.

As previously discussed, the specification section will be updated each time the site is rebuilt. From what I understood, this was ok.

If we want to rebuilt the site each time a change is submitted to the specification repo, we should consider my proposed solution https://github.com/jakartaee/jakarta.ee/pull/357#issuecomment-512410368

This is something that I believe we must implement on the specification repo, not this website.

**Comment by waynebeaton** [comment]
> As previously discussed, the specification section will be updated each time the site is rebuilt. From what I understood, this was ok.

It will be the Jakarta EE Specification Committee that will decide when they need the content to be updated (i.e., when the site will need to be rebuilt). By what means should that request be made? e.g., an email or GitHub issue? We'll likely only need it rebuilt a few times over the next six weeks or so.

**Comment by chrisguindon** [comment]
@waynebeaton Github issue would be the way to go for now!

**Pull request merged**
