### PR TITLE
Release 9 page visual tweks

### PR DESCRIPTION
**Pull request by Dexmaster**
- square off card corners
- tweak card shadows
- make feature cards same height if in one line
- tweaked hr and br styles

Signed-off-by: Andrii Malytskyi <amalytskyi@tomitribe.com>

### CODE REVIEW

**Comment by Dexmaster** [comment]
@chrisguindon Here is a continuation about visual tweaks ( which I mentioned in PR #923 )

Ready for review.

**Comment by aeiras** [comment]
Let me just say how much I love this follow up from Contributors' Card PR :) 
Thank you Andrii and Chris for keeping stuff focused and for playing ball with openness! 

Abrazos,

**Comment by chrisguindon** [comment]
+1 LGTM!

Thanks @Dexmaster and @aeiras

**Comment by aeiras** [comment]
The two of you are on fire Chris and Andrii :) 
This is potentially a record merging feature on any Jakarta EE PR.  It makes front-end with a high focus on UX goal collaboration extra fun!

**NOW** if we could only get this https://github.com/jakartaee/jakarta.ee/pull/879  Announcement PR completed... that would be incredible.  There are too many politics involved to allow for a healthier / conclusion.  

Let's stay possitive, 

However, Chris-- your time is appreciated on that ticket. Super helpful insights too. Thanks!

**Pull request merged**
