### PR TITLE
Generate projects page

### PR DESCRIPTION
**Pull request by jgallimore**
This PR combines #159 and #344, rebases and merges the conflicts. Thanks @ggam for your PR to keep this going.

Side note, I encounter rate limits when running without authentication, but add a token into generate-project-pages.js seems to work just fine.

Sample output below.
Snip20190725_1

### CODE REVIEW

**Comment by chrisguindon** [comment]
> Side note, I encounter rate limits when running without authentication, but add a token into generate-project-pages.js seems to work just fine.

There is a $GITHUB_TOKEN available but i am a bit concerned about security since we would need to write a script to inject the token in your js script. The token could be leaked if this is not done correctly:

- https://github.com/jakartaee/jakarta.ee/blob/src/.travis.yml
- https://docs.travis-ci.com/user/encryption-keys/

**Comment by jgallimore** [comment]
That was my worry too. Thanks for the link, I'll take a look and see if can
hook something up.

**Comment by chrisguindon** [comment]
As a follow up, my team is currently working on a new API endpoint for project data. For example, you can fetch all the jakarta-ee projects via this call:

https://projects.eclipse.org/api/projects?working_groups=jakarta-ee

Please note that the result are paginated via the Link response header. My team is currently working on publishing the official document of this new endpoint.

**Comment by ggam** [comment]
That's definitely more sustainable in the long run. Can we also get the profile photo url? I'd like to list the commiters and contributors for projects. For the contributors, we can use the GitHub API but the committer data is from Eclipse.

Do you have any ETA for the documentation?

**Comment by chrisguindon** [comment]
>  Can we also get the profile photo url?

We can and we should include the profile picture in our profile endpoint:
https://api.eclipse.org/account/profile/cguindon/

I will open a bug on Eclipse Bugzilla for that.

> Do you have any ETA for the documentation?

Without making any promises, my best guess is that we should have something within 2 weeks as we are still making some tweaks to this new API endpoint.

**Comment by chrisguindon** [comment]
Profile picture created:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=551382

**Comment by ggam** [comment]
Awesome. If @jgallimore doesn't have time for this I may take a look at it
myself on the weekend.

**Comment by jgallimore** [comment]
Finding time is proving a little difficult, so extra help is definitely
welcome, thank you!

**Comment by ggam** [comment]
I'll let you know if I start working at it so we don't duplicate efforts

**Comment by chrisguindon** [comment]
I am currently in the process of upgrading the jakarta.ee website to the latest version of Hugo and our [eclipsefdn-hugo-solstice theme](https://github.com/EclipseFdn/hugo-solstice-theme).

While doing so, I am leveraging this exercise to test our new Project component which can fetch project data from our Api:
https://eclipsefdn-hugo-solstice-theme.netlify.com/components/eclipsefdn_projects/

A preview is available here:
https://deploy-preview-586--jakartaee.netlify.com/projects/

Is this something that we should use on the website?

> Can we also get the profile photo url?

Photo url is now included:
https://api.eclipse.org/account/profile/cguindon/

> Do you have any ETA for the documentation?
Documentation is live: https://api.eclipse.org/#tag/Projects

**Comment by ggam** [comment]
@chrisguindon very solid start. We can work from that once it's merged.

**Comment by chrisguindon** [comment]
The new project page is now available on the website:
https://jakarta.ee/projects/

The projects link on the homepage was updated to point to this new page. 

EMO is currently responsible for managing the list of projects on this page from projects.eclipse.org. 

Please open an issue if we are missing a project of if you think we should remove a project from this page.

**Comment by chrisguindon** [comment]
Is someone planning to work on this or should we close this PR?

**Comment by chrisguindon** [comment]
I am going to close this issue since there is no activity on the PR. Please re-open if someone wish to pick this up again!

**Pull request closed without merging**
