### PR TITLE
Add 2020 Survey Infographic to jakarta.ee... #1103

### LINKED ISSUE #1103: Add 2020 Survey Infographic to jakarta.ee/resources/
Can we add the link below to the resources page under **Infographics**?

TEXT: Jakarta EE Developer Survey Findings 2020

LINK: https://f.hubspotusercontent30.net/hubfs/4753786/JakartaEE-Infographic.pdf?utm_campaign=2021%20Jakarta%20EE%20Developer%20Survey&utm_source=resources

### PR DESCRIPTION
**Pull request by autumnfound**
Fixes #1103

### CODE REVIEW

**Comment by autumnfound** [comment]
Currently missing Chinese translation of the text. Should we reach out Eric?

**Comment by karenmcnaughton** [comment]
yes pls

**Comment by chrisguindon** [comment]
+1 

@laliwa,

How would you recommend we proceed when we need a Chinese translation? Would you expect us to ping you each time we make an update?

or are we simply planning to periodically refresh the Chinese translation? It not clear to me how the WG would like to handle the Chinese transition on the site.

**Comment by laliwa** [comment]
> +1
> 
> @laliwa,
> 
> How would you recommend we proceed when we need a Chinese translation? Would you expect us to ping you each time we make an update?
> 
> or are we simply planning to periodically refresh the Chinese translation? It not clear to me how the WG would like to handle the Chinese transition on the site.

In my opinion, give me a ping whenever there is a change will be a better solution. Only if that will not bother you too much ;-)

**Comment by chrisguindon** [comment]
@laliwa,

+1 How about we do this moving forward.

We add English to the Chinese website by default and we go live with our changes to avoid holding off an update for a translation. Then, we open an issue asking you to translate the new text?

//cc @ericpoirier @autumnfound

**Comment by laliwa** [comment]
> @laliwa,
> 
> +1 How about we do this moving forward.
> 
> We add English to the Chinese website by default and we go live with our changes to avoid holding off an update for a translation. Then, we open an issue asking you to translate the new text?
> 
> //cc @ericpoirier @autumnfound

Yes, that sounds OK to me.

**Pull request merged**
