### PR TITLE
remove upcoming text #1022

### LINKED ISSUE #1022: Launch Jakarta EE 9 page
The go live for the Jakarta EE 9 page is late in the day on December 7th please.
Can you remove the text: "Jakarta EE 9 is coming on December 8" before go live.

//cc @karenmcnaughton

### PR DESCRIPTION
**Pull request by flora8984461**
Fix #1022 

Signed-off-by: Yi Liu <yi.liu@eclipse-foundation.org>

### CODE REVIEW

**Review by autumnfound — APPROVED** [review]

**Comment by autumnfound** [comment]
Do we want to hold off on this change, or merge it now?

**Comment by flora8984461** [comment]
> Do we want to hold off on this change, or merge it now?

Chris said later today, probably in the afternoon? 🤔 @chrisguindon

**Comment by chrisguindon** [comment]
@autumnfound I am planing to merge this PR this afternoon.

**Comment by karenmcnaughton** [comment]
Looks good to me @flora8984461 thanks!

**Pull request merged**
