### PR TITLE
Update links to TCK results

### PR DESCRIPTION
**Pull request by Thharrison**
Signed-off-by: Theo Harrison <thharrison001@gmail.com>

### CODE REVIEW

**Comment by Thharrison** [comment]
This addresses issue #861

**Comment by jgallimore** [comment]
retest this please

**Comment by jgallimore** [comment]
@TanjaObradovic I know that Theo has updated (or attemped to update) the email address on his Eclipse Account, and has signed the ECA. Could someone take a look at his Eclipse account please?

**Comment by jgallimore** [comment]
This looks good to me.

**Comment by chrisguindon** [comment]
Information about commits are available via the Github API:
https://api.github.com/repos/jakartaee/jakarta.ee/pulls/870/commits

I was not able to locate an Eclipse account with the theo@.. email address.

**Comment by chrisguindon** [comment]
@ivargrimstad I defer to you if this is something that should be merged!

**Review by ivargrimstad — APPROVED** [review]
Great job!

**Pull request merged**
