### PR TITLE
update jesp for service releases

### PR DESCRIPTION
**Pull request by kwsutter**
Signed-off-by: Kevin Sutter <kwsutter@gmail.com>

Updating the JESP per the discussion on the Spec Committee call on Jan 13 concerning the service release process.  Corresponding changes are being done in the Ops Guide via PR #1047.  Since there are different requirements for approving changes to the JESP vs the Ops Guide, these two PRs are separate.  Thanks!

Two other minor updates were also performed via this PR:
* Specification was missing the second "c".
* There was an extra space before "per year".

I will first ask for @ivargrimstad's review before asking for the spec committee membership for review and approval.  Once that is done, I will take this PR out of draft mode and it can be merged.

### CODE REVIEW

**Comment by waynebeaton** [comment]
It looks like you just copied some bits from the EFSP.

My concern is that copying this information to this document without including the part where a [specification committee ballot is required](https://github.com/EclipseFdn/EFSP/blob/master/source/process.adoc#approvals) for a service release may be misleading.

**Comment by kwsutter** [comment]
> It looks like you just copied some bits from the EFSP.

Yes, I copied and modified the section on Service Releases from the EFSP.  That's the approach that was decided on the Spec Committee call.  We were trying to clarify what a Service Release allows (ie. no functional changes) and that a Release Review was **not** required for a Service Release.

> 
> My concern is that copying this information to this document without including the part where a [specification committee ballot is required](https://github.com/EclipseFdn/EFSP/blob/master/source/process.adoc#approvals) for a service release may be misleading.

Thanks for pointing out this other item where a super majority vote is required for a Service Release.  Do you see an issue with us not requiring a super majority vote?  If we're good with this approach, then I can add a modification for this section as well.

**Comment by waynebeaton** [comment]
> Do you see an issue with us not requiring a super majority vote?

My interpretation is that this requirement cannot be overridden.

**Comment by ivargrimstad** [comment]
> > Do you see an issue with us not requiring a super majority vote?
> 
> My interpretation is that this requirement cannot be overridden.

**Comment by ivargrimstad** [comment]
> > Do you see an issue with us not requiring a super majority vote?
> 
> My interpretation is that this requirement cannot be overridden.

I guess we will need to file an issue for changes to the EFSP then?

**Comment by waynebeaton** [comment]
> I guess we will need to file an issue for changes to the EFSP then?

Yup.

FWIW, the process is written as it is because the committee that created the process decided that this was a requirement.

**Comment by kwsutter** [comment]
> > I guess we will need to file an issue for changes to the EFSP then?
> 
> Yup.
> 
> FWIW, the process is written as it is because the committee that created the process decided that this was a requirement.

And, basically, that same committee is now deciding that this was overkill...  :-)

**Comment by kwsutter** [comment]
I will be submitting this PR for ballot approval to the Spec Committee later today.  Upon a successful ballot, the results will be communicated to the Steering Committee on Mar 2, 2021.

In parallel, similar changes are being proposed for the EFSP via https://github.com/EclipseFdn/EFSP/issues/29.  Upon resolution of that Issue, we may need to come back to the JESP and make some corresponding updates.  But, for now, we're moving forward with the proposed update to the JESP so that we can make progress.

**Comment by kwsutter** [comment]
With the unanimous approval from both the Specification and Steering Committees, this PR is ready to be merged.  Thank you!

From the (draft) minutes of our Mar 2 meeting:

> Discussion:
> Kevin presented the issue (described above) -- **Unanimous approval** by Spec. committee members.
> Would like to call a super-majority vote on a resolution to adopt JESP 1.3 proposal as drafted.
> Fujitsu  - yes
> IBM - yes
> Oracle - yes
> Payara - yes
> Red Hat - yes
> Tomitribe - yes
> Participant member representative - yes
> The resolution passed with **unanimous approval** of members present.

**Comment by kwsutter** [comment]
@chrisguindon or @flora8984461, could we go ahead with the merge of this PR and the corresponding update to the Ops Guide (PR #1047)?  Thanks!

**Comment by chrisguindon** [comment]
@kwsutter Done!

Please let me know if you need us for anything else!

**Pull request merged**
