### PR TITLE
Update FAQ text contents #1002

### LINKED ISSUE #1002: Update the FAQ on the Jakarta EE website
We have an update to the FAQ for the Jakarta EE website--the current one is located here:
https://jakarta.ee/about/faq/

The updated text can be found here: https://docs.google.com/document/d/1-ZjjP81SHrgLO_hp2LAQ5JEWKU8tT_drqi6WPphkS6E/edit#

### PR DESCRIPTION
**Pull request by flora8984461**
Fix #1002 

I have not added Chinese faq JSON in this PR since I am waiting for https://github.com/jakartaee/jakarta.ee/pull/1004 (have Chinese faq json) to be merged.

Hi @laliwa , we have updated some FAQ contents, and we are switching to use JSON files for FAQ so that it can be suitable for SEO.

The updated English FAQ JSON file is [here](https://github.com/jakartaee/jakarta.ee/pull/1009/files#diff-84320d0a077dd486e3b97c1c79a6d2d834d8bed9bde525cabb3b7454ad9cd3d0).

I have included old Chinese FAQ contents in the FAQ JSON file [here](https://github.com/jakartaee/jakarta.ee/pull/1004/files#diff-f2baa80bd6478a41c2c1b256ccaf89c3c5281a29b9e5dd525cd96a3613ae7309). 

Would you mind taking a look at the updated contents and help us with the translation? 

The two files are separated due to different PRs, they will be together once we make a release of new Hugo theme.

Thanks!

Signed-off-by: Yi Liu <yi.liu@eclipse-foundation.org>

### CODE REVIEW

**Comment by flora8984461** [comment]
We probably need Chinese translation for updated content? 🤔

**Comment by laliwa** [comment]
> Fix #1002
> 
> I have not added Chinese faq JSON in this PR since I am waiting for #1004 (have Chinese faq json) to be merged.
> 
> Hi @laliwa , we have updated some FAQ contents, and we are switching to use JSON files for FAQ so that it can be suitable for SEO.
> 
> The updated English FAQ JSON file is [here](https://github.com/jakartaee/jakarta.ee/pull/1009/files#diff-84320d0a077dd486e3b97c1c79a6d2d834d8bed9bde525cabb3b7454ad9cd3d0).
> 
> I have included old Chinese FAQ contents in the FAQ JSON file [here](https://github.com/jakartaee/jakarta.ee/pull/1004/files#diff-f2baa80bd6478a41c2c1b256ccaf89c3c5281a29b9e5dd525cd96a3613ae7309).
> 
> Would you mind taking a look at the updated contents and help us with the translation?
> 
> The two files are separated due to different PRs, they will be together once we make a release of new Hugo theme.
> 
> Thanks!
> 
> Signed-off-by: Yi Liu [yi.liu@eclipse-foundation.org](mailto:yi.liu@eclipse-foundation.org)

Sure, I made one here https://github.com/jakartaeechina/jakarta.ee/blob/src/data/zh/faq.json

**Comment by flora8984461** [comment]
@laliwa Thank you so much! I have included it in this https://github.com/jakartaee/jakarta.ee/pull/1004 pull request since we want to combine updating faq together in one PR. 

Please feel free to check the preview in https://github.com/jakartaee/jakarta.ee/pull/1004.

Thanks!

**Comment by laliwa** [comment]
Great!






------------------

  	Eric (QingYu Meng)&nbsp; 	&nbsp;Marketing Director
 	--------------
 	Primeton Software, Inc. (Stock Code: 688118)
 	Specialize in - Digital Middle Platform - Digital Transformation Accelerating
 
 

&nbsp;
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------

**Pull request closed without merging**
