### PR TITLE
Restructure schemas page

### PR DESCRIPTION
**Pull request by ivargrimstad**
Signed-off-by: Ivar Grimstad <ivar.grimstad@eclipse-foundation.org>

### CODE REVIEW

**Comment by ivargrimstad** [comment]
This one is ready

**Comment by chrisguindon** [comment]
@ivargrimstad fell free to add my as a reviewer if you need me to look at this!

**Comment by ivargrimstad** [comment]
@chrisguindon I don't have the access rights to add reviewers, but please review :)

**Comment by ivargrimstad** [comment]
Wait with merging this until https://github.com/jakartaee/jakarta.ee/pull/707 has been merged.
I will update this PR with the changes afterward.

**Comment by chrisguindon** [comment]
I will fix that permission issue for you @ivargrimstad

**Pull request closed without merging**
