### PR TITLE
CSP: images with data url are blocked

### PR DESCRIPTION
**Pull request by hussainnm**
Add scheme data and https for image source in CSP directive

### CODE REVIEW

**Comment by hussainnm** [comment]
For comparison, the images are not loading.
Current:
https://jakarta.ee/specifications/platform/10/jakarta-platform-spec-10.0.html#architecture

PR:
https://deploy-preview-1643--jakartaee.netlify.app/specifications/platform/10/jakarta-platform-spec-10.0.html#architecture

**Comment by hussainnm** [comment]
Please review @mbarbero @chrisguindon

**Comment by mbarbero** [comment]
lgtm 👍

**Review by mbarbero — APPROVED** [review]

**Comment by chrisguindon** [comment]
Thanks for the fix @hussainnm

**Pull request merged**
