### PR TITLE
Updated Jakarta EE Committee Members

### LINKED ISSUE #1301: Jakarta EE Committee Members update
Can you please update the Committee Members section on the following pages

https://jakarta.ee/committees/steering/

- Will Lyons (chair)- Oracle, Ed Bratt - alternate
- Kenji Kazumura - Fujitsu, Yuichi Kusano - alternate
- Ian Robinson - IBM, Alasdair Nottingham - alternate
- Steve Millidge - Payara, Eliot Martin - alternate
- Mark Little - Red Hat, Scott Stark - alternate
- David Blevins - Tomitribe, Cesar Hernandez - alternate
- Martijn Verburg - London Java Community - Elected Participant Member Representative
- Arjan Tijms - Elected Committer Member Representative
- Dr. Jun Qian - Primeton - Elected Enterprise Representative
- Zhao Xin - Shandong Cvicse Middleware Co. - Elected Enterprise Representative

https://jakarta.ee/committees/specification/

- Kenji Kazumura - Fujitsu
- Kevin Sutter - IBM, Tom Watson - alternate
- Ed Bratt - Oracle, Dmitry Kornilov - alternate
- Andrew Pielage - Payara
- Scott Stark - Red Hat, Mark Little - alternate
- David Blevins - Tomitribe, Jean-Louis Monterio - alternate
- Ivar Grimstad - PMC Representative
- Marcelo Ancelmo - London Java Community - Elected Participant Member Representative, Martijn Verburg - alternate
- Werner Keil - Elected Committer Member Representative
- Dr. Jun Qian - Primeton - Elected Enterprise Representative
- Zhai Luchao - Shandong Cvicse Middleware Co. - Elected Enterprise Representative
- Paul Buck - Eclipse Foundation (serves as chair, but is not a voting committee member)

https://jakarta.ee/committees/marketing/

- Kenji Kazumura - Fujitsu, Yuichi Kusano - alternate
- Neil Patterson (chair) - IBM
- Ed Bratt - Oracle, Melissa Jacobus - alternate
- Dominika Tasarz - Payara, Jadon Ortlepp - alternate
- John Clingan - Red Hat
- Jonathan Gallimore - Tomitribe, Cesar Hernandez - alternate
- Eric (QingYu) Meng - Primeton - Elected Enterprise Representative
- Zhao Xin Cvicse - Shandong Cvicse Middleware - Enterprise Member
- Otavio Santana - Elected Committer Member Representative
- Tetiana Fydorenchyk - Elected Participant Member Representative

### PR DESCRIPTION
**Pull request by linkfang**
Fixes [issue1301](https://github.com/jakartaee/jakarta.ee/issues/1301)

### CODE REVIEW

**Comment by TanjaObradovic** [comment]
I have made a mistake on the Marketing Cmtee page
instead of 
Zhao Xin Cvicse - Shandong Cvicse Middleware - Enterprise Member
it should be 
Zhao Xin Cvicse - Shandong Cvicse Middleware - Elected Enterprise Member

**Comment by linkfang** [comment]
> I have made a mistake on the Marketing Cmtee page instead of Zhao Xin Cvicse - Shandong Cvicse Middleware - Enterprise Member it should be Zhao Xin Cvicse - Shandong Cvicse Middleware - Elected Enterprise Member

Cool, I was typing in the issue trying to confirm her name.

Cvicse doesn't seem to be part of the person's name but the company name. And we do have the same person on committees/steering/ list, and the name is just Zhao Xin.

So, should we remove the Cvicse from her name and just keep it in the company name?

**Comment by TanjaObradovic** [comment]
Thanks so much for pointing out! 

The correct entry should be this:

Zhao Xin - Shandong Cvicse Middleware Co. - Elected Enterprise Representative

I was trying to correct what was there previously and messed it up even further!

**Comment by linkfang** [comment]
No problem!

The preview page is available now:
https://deploy-preview-1302--jakartaee.netlify.app/committees/marketing/
https://deploy-preview-1302--jakartaee.netlify.app/committees/specification/
https://deploy-preview-1302--jakartaee.netlify.app/committees/steering/

**Comment by TanjaObradovic** [comment]
looks great! thanks!

**Review by ericpoirier — APPROVED** [review]

**Pull request merged**
