### PR TITLE
Add documentation for creating a new entry in https://jakarta.ee/news/

### PR DESCRIPTION
**Pull request by cesarhernandezgt**
Solves #1196 1196

### CODE REVIEW

**Comment by chrisguindon** [comment]
I think what is missing here is some information about how is allowed to publish content under that section? 

I would also like to understand who is responsible for approving the content.

**Comment by cesarhernandezgt** [comment]
Thanks for the feedback @chrisguindon.

> I think what is missing here is some information about how is allowed to publish content under that section?

As mentioned in https://github.com/jakartaee/jakarta.ee/issues/880#issuecomment-689057516, the /news content represents official news and announcements made by the Jakarta EE Working Group.
 
> I would also like to understand who is responsible for approving the content.

The /news section is part of the `Resource` menu, base on https://docs.google.com/spreadsheets/d/1efy2BjsB4zfxNGIA7ESXL_bgXZKfpfHJlRMt19zzuro/edit#gid=98299565, the responsibility for approving content is the Eclipse Foundation Marketing Manager. I updated the PR to state this in 134596e

**Review by chrisguindon — APPROVED** [review]

**Comment by aeiras** [comment]
@chrisguindon & @TanjaObradovic, 
Thank you and the team for helping us move forward to complete this task. We appreciate our collaboration with you! 

@cesarhernandezgt's work on anything related to the EE 9.1 page **ends** tomorrow. 
We hope that any issues with this particular task are raised before the invested time expires.  

Should any unknown issues push this ticket to next week, you are welcomed to add me, **instead of Cesar**.

**Comment by autumnfound** [comment]
@TanjaObradovic Could you take a look at this? I'd like your +1 before merging.

**Comment by TanjaObradovic** [comment]
@karenmcnaughton can you please review this one?
Looks good to go to me.

**Comment by cesarhernandezgt** [comment]
@karenmcnaughton 
Can you please review this  PR. As you can see the, PR is an internal website documentation update and doesn't impact any front-facing page from jakarta.ee website.

**Comment by shabnammayel** [comment]
LGTM

**Pull request merged**
