### PR TITLE
Add Open liberty jakarta ee 9 platform

### LINKED ISSUE #1078: Open Liberty 21.0.0.3-beta as a Compatible Software Product for Jakarta EE 9, Platform
To include your Compatible Software Product on the Jakarta EE official list of Compatible Software Products, please provide the following information:

**The URL to the Eclipse Foundation profile to confirm that you are an authorized representative of the company whose product information you are submitting**
[Brian Decker - IBM - Eclipse Profile](https://accounts.eclipse.org/users/bdeckerhdt)

**A product name and version**
[Open Liberty 21.0.0.3-beta](https://openliberty.io/)

**The Profile (Full Platform, Web Profile, Both) that the Compatible Product is submitted to be listed under**
Full Platform

**A ZIP file with a product logo with a transparent background in SVG format (optional)**
[https://openliberty.io/certifications/assets/OL_logo_navy.zip](https://openliberty.io/certifications/assets/OL_logo_navy.zip)

**The Participant, Enterprise or Strategic Member name supporting the Compatible Software Product**
[IBM Corporation](https://www.ibm.com/)

**The URL to the approved certification issue demonstrating compatibility as defined in the Jakarta EE TCK Process**
Full Platform: [https://github.com/eclipse-ee4j/jakartaee-platform/issues/307](https://github.com/eclipse-ee4j/jakartaee-platform/issues/307)

**The URL where Compatible Software Product is available for download**
[https://openliberty.io/downloads/#runtime_betas](https://openliberty.io/downloads/#runtime_betas)

### PR DESCRIPTION
**Pull request by flora8984461**
Fix #1078 

Signed-off-by: Yi Liu <yi.liu@eclipse-foundation.org>

### CODE REVIEW

**Comment by flora8984461** [comment]
Hi Tanja @TanjaObradovic , can you help us check the preview link to verify the compatibility product is expected?

https://deploy-preview-1081--jakartaee.netlify.app/compatibility/#tab-9

Thanks!

**Review by autumnfound — APPROVED** [review]

**Comment by ivargrimstad** [comment]
Please wait for the `accepted` label to be set on the Certification Issue, https://github.com/eclipse-ee4j/jakartaee-platform/issues/307.

**Comment by brideck** [comment]
The `accepted` label has now been set on the Certification issue.  Please merge this at your earliest convenience.

**Comment by chrisguindon** [comment]
Thanks for the ping @brideck

**Pull request merged**
