### PR TITLE
Update Hugo version to Fix IE JS

### PR DESCRIPTION
**Pull request by autumnfound**
Signed-off-by: Martin Lowe <martin.lowe@eclipse-foundation.org>

### CODE REVIEW

**Comment by flora8984461** [comment]
Still a small problem on Jarkata.ee site.

image

image

**Comment by autumnfound** [comment]
> Still a small problem on Jarkata.ee site.
> 
> image
> 
> image

This is related to just the featured footer and story. We can create a separate issue to track this in this repo! This wasn't caused by the Hugo update, and doesn't block the rest of the site from working.

**Review by flora8984461 — APPROVED** [review]

**Review by ericpoirier — APPROVED** [review]
Related to Yi's note, I'm seeing the featured story properly now.

**Comment by chrisguindon** [comment]
@autumnfound @flora8984461 @ericpoirier I created https://github.com/EclipseFdn/hugo-solstice-theme/issues/162 to track this issue. 

Hopefully, we can fix this issue this week to allow us to fix this on jakarta.ee and science.eclipse.org.

Am I missing any other sites?

**Pull request merged**
