### PR TITLE
Update batch XSDs to version 2.0

### PR DESCRIPTION
**Pull request by scottkurz**
Signed-off-by: Scott Kurz <skurz@us.ibm.com>

Following Jakarta EE 9 convention , have the "version" attribute for the top-level element ("job") match the spec version and file name... so bump up from 1.0 to 2.0.

The earlier PR #707 converted the target NS of the schema elements but it left the version as 1.0.

### CODE REVIEW

**Comment by chrisguindon** [comment]
Sorry - I added Ivar for review only to notice that this was still a work in progress.

**Comment by scottkurz** [comment]
@chrisguindon , @ivargrimstad - please go ahead and review.  

The matching PR in 'batch-api':  https://github.com/eclipse-ee4j/batch-api/pull/103   has been reviewed (unfortunately we have the files duplicated across the two projects, but changes should be rare).

Thank you.

**Comment by ivargrimstad** [comment]
Hmm...that was weird. I changed the destination branch to be `src`. Caused the PR to be closed. And I don't seem able to reopen it. @chrisguindon Any suggestions?

**Comment by scottkurz** [comment]
@ivargrimstad do you want me to rebase on 'src' and open a new PR?

**Comment by ivargrimstad** [comment]
@scottkurz Yes, please :) The src is where we merge the changes to. Then the CI picks it up and commits to master.

**Pull request closed without merging**
