### PR TITLE
#255 - Add compatibility page and issue template

### PR DESCRIPTION
**Pull request by ericpoirier**
Signed-off-by: Eric Poirier <eric.poirier@eclipse-foundation.org>

### CODE REVIEW

**Comment by chrisguindon** [comment]
My concern here is that we are adding yet another top level item for a new page.

May I propose that we move "Blog" under "Resources" if we are going to add a "Compatibility" menu item?

@stephanieswart @TanjaObradovic What do you think?

**Comment by TanjaObradovic** [comment]
I will let Stephanie have the final say on this one. I think I am ok with it, but it is nice to have "blog" on it own :). I guess Jakarta EE is growing and it makes sense to move things around.

**Comment by stephanieswart** [comment]
Personally, I don't think we should hide blogs under resources as I don't think that a blog is a resource, it's an ongoing center of information. I think there will be less visibility on it unless maybe the community news section could automatically update with every new blog post that comes in. However, if we'd like to remove blog from the navigation bar, I think we need to implement something to make up for the lack of visibility.

**Comment by TanjaObradovic** [comment]
+1 with Stephanie's comment

**Comment by chrisguindon** [comment]
The problem that I am trying to highlight is that we can't add a new top level item for each new page since will run out of space. 

I think this issue is showing us that we need to improve our content strategy.

For example, eclipse.org is a website with way more content and we only have 3 top level links (Members, Working Groups and Projects). 

Perhaps it's time to bring back the more menu to include links such as all the ressources. I personally would move blogs under the more menu as we are doing with www.eclipse.org and planeteclipse.org.

Also,  the "Specification Process" section in the resource dropdown is not very useful. We are linking to a google drive documents that is NOT public and to a CFP proposal from 2018.

**Comment by chrisguindon** [comment]
Let's merge this change since @TanjaObradovic is waiting for this to go live but I am hoping that the marketing team will take in considerations my recommendations for the future!

**Pull request merged**
