### PR TITLE
Correct link. Closes #1032

### LINKED ISSUE #1032: Compatibility Request Link Broken
**Describe the bug**
The "Compatibility Requests" link is malformed (it is missing a .) and results in an inability to resolve the hostname.

**To Reproduce**
1. Go to 'https://jakarta.ee/compatibility/'
2. Click on 'Compatibility Requests'
4. See error.

**Expected behavior**
You would expect to be directed to: https://github.com/eclipse-ee4j/jakartaee-platform/issues?q=is%3Aissue+is%3Aclosed+label%3Acertification

### PR DESCRIPTION
**Pull request by ivargrimstad**
Signed-off-by: Ivar Grimstad <ivar.grimstad@eclipse-foundation.org>

### CODE REVIEW

**Review by flora8984461 — APPROVED** [review]
nice catch! thanks.

**Review by flora8984461 — COMMENTED** [review]
Sorry for my miss, this https://github.com/ivargrimstad/jakarta.ee/blob/fix-ccr-link/layouts/shortcodes/pages/compatibility-products.html also needs this fix. I can add it if you like.

**Comment by flora8984461** [comment]
> Sorry for my miss, this https://github.com/ivargrimstad/jakarta.ee/blob/fix-ccr-link/layouts/shortcodes/pages/compatibility-products.html also needs this fix. I can add it if you like.

I added https://github.com/jakartaee/jakarta.ee/pull/1034

**Comment by chrisguindon** [comment]
THis was fix with https://github.com/jakartaee/jakarta.ee/pull/1035

**Pull request closed without merging**
