### PR TITLE
Updated the version of Red Hat JBoss

### LINKED ISSUE #1243: Please update to show Red Hat JBoss Enterprise Application Platform 7.4.0.GA as both Full Platform + Web Profile compatible
Please update the entry for `JBoss Enterprise Application Platform` on https://jakarta.ee/compatibility/#tab-8 to [7.4.0](https://github.com/RedHatOfficial/jbosseap-certifications/blob/EE8/EAP-7.4.0/jakarta-full-platform.adoc#tck-results).  Below are the normally expected items for this request...  Thank you!  -Scott

To include your Compatible Software Product on the Jakarta EE official list of Compatible Software Products, please provide the following information:

**The URL to the Eclipse Foundation profile to confirm that you are an authorized representative of the company whose product information you are submitting**
https://www.eclipse.org/membership/showMember.php?member_id=731

**A product name and version**
Red Hat JBoss Enterprise Application Platform 7.4.0.GA

**The Profile (Full Platform, Web Profile, Both) that the Compatible Product is submitted to be listed under**
Both

**A ZIP file with a product logo with a transparent background in SVG format (optional)**
https://github.com/RedHatOfficial/jbosseap-certifications/blob/EE8/images/Logo-Red_Hat-JBoss_Enterprise_Application_Platform-B-Standard-RGB.png

**The Participant, Enterprise or Strategic Member name supporting the Compatible Software Product**
Red Hat

**The URL to the approved certification issue demonstrating compatibility as defined in the Jakarta EE TCK Process**
https://github.com/eclipse-ee4j/jakartaee-platform/issues/389
https://github.com/eclipse-ee4j/jakartaee-platform/issues/390

**The URL where Compatible Software Product is available for download**
http://www.redhat.com/en/technologies/jboss-middleware/application-platform

### PR DESCRIPTION
**Pull request by linkfang**
Fixes [issue1243](https://github.com/jakartaee/jakarta.ee/issues/1243)

### CODE REVIEW

**Comment by autumnfound** [comment]
Hold off on merging this until it has been approved in the certification request

**Review by autumnfound — APPROVED** [review]

**Comment by ericpoirier** [comment]
> Hold off on merging this until it has been approved in the certification request

How will we know when it's approved?

**Comment by autumnfound** [comment]
> > Hold off on merging this until it has been approved in the certification request
> 
> How will we know when it's approved?

The issues referenced for certification requests will have the `accepted` tag/label in my past experience. While this product technically passes the TCK likely, we want to be sure that people who manage the request for acceptance agree  

The URL to the approved certification issue demonstrating compatibility as defined in the Jakarta EE TCK Process
eclipse-ee4j/jakartaee-platform#389
eclipse-ee4j/jakartaee-platform#390

**Comment by ericpoirier** [comment]
> > > Hold off on merging this until it has been approved in the certification request
> > 
> > 
> > How will we know when it's approved?
> 
> The issues referenced for certification requests will have the `accepted` tag/label in my past experience. While this product technically passes the TCK likely, we want to be sure that people who manage the request for acceptance agree
> 
> The URL to the approved certification issue demonstrating compatibility as defined in the Jakarta EE TCK Process
> [eclipse-ee4j/jakartaee-platform#389](https://github.com/eclipse-ee4j/jakartaee-platform/issues/389)
> [eclipse-ee4j/jakartaee-platform#390](https://github.com/eclipse-ee4j/jakartaee-platform/issues/390)

Ok got it. I subscribed to the issue so whenever there's an update i'll get a notification.

**Review by scottmarlow — APPROVED** [review]

**Comment by ivargrimstad** [comment]
> Ok got it. I subscribed to the issue so whenever there's an update i'll get a notification.

The issues are approved, marked as accepted, and closed, so you are good to go with the merge.

**Pull request merged**
