### PR TITLE
Added Chinese translation for 2020 survey infographic to Jakarta.ee

### PR DESCRIPTION
**Pull request by linkfang**

### CODE REVIEW

**Comment by linkfang** [comment]
Hi @laliwa , 

Let me know what do you think about this translation:
"Jakarta EE Developer Survey Findings 2020" to "2020 Jakarta EE 开发者调研结果"

Thanks!

**Review by autumnfound — COMMENTED** [review]
LGTM, I can wait a few days for +1 on actual content approval as well!

**Review by autumnfound — APPROVED** [review]

**Comment by laliwa** [comment]
> Hi @laliwa ,
> 
> Let me know what do you think about this translation:
> "Jakarta EE Developer Survey Findings 2020" to "2020 Jakarta EE 开发者调研结果"
> 
> Thanks!

Sounds OK to me. It can also be "2020年Jakarta EE 开发者调研发现"

**Comment by linkfang** [comment]
> Sounds OK to me. It can also be "2020年Jakarta EE 开发者调研发现"

Cool! 
I do think adding a "年" into it feels much better. 
So, to make it consistent with "2018 Jakarta EE 调研图表", maybe add "年" to both of them?

Like "2018年 Jakarta EE 调研图表" and "2020年 Jakarta EE 开发者调研结果"
What do you think?

**Comment by laliwa** [comment]
Great!






------------------

  	Eric (QingYu Meng)&nbsp; 	&nbsp;Marketing Director
 	--------------
 	Primeton Software, Inc. (Stock Code: 688118)
 	Specialize in - Digital Middle Platform - Digital Transformation Accelerating
 
 

&nbsp;
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: &nbsp;"Zhou (Link) ***@***.***&gt;;
Date: &nbsp;Fri, May 7, 2021 02:21 AM
To: ***@***.***&gt;; 
Cc: &nbsp;"Eric.Meng@***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [jakartaee/jakarta.ee] Added Chinese translation for 2020 survey infographic to Jakarta.ee (#1132)

&nbsp;



  
Sounds OK to me. It can also be "2020年Jakarta EE 开发者调研发现"
  
Cool!
 I do think adding a "年" into it feels much better.
 So, to make it consistent with "2018 Jakarta EE 调研图表", maybe add "年" to both of them?
 
Like "2018年 Jakarta EE 调研图表" and "2020年 Jakarta EE 开发者调研结果"
 What do you think?

**Pull request merged**
