### PR TITLE
Add location for Jakarta EE XML Schemas to fix #592

### LINKED ISSUE #592: XML Namespace under Jakarta
**Is your feature request related to a problem? Please describe.**
We need to replace the JCP namespaces in the XML documents with Jakarta, which means we need a location for the XML Schemas (XSDs).

**Describe the solution you'd like**
Make the schemas from https://github.com/eclipse-ee4j/jakartaee-schemas available under https://jakarta.ee/xml/ns/jakartaee/

As an example, look at how it was done under the JCP here: http://xmlns.jcp.org/xml/ns/javaee

**Describe alternatives you've considered**
Consider creating a subdomain like https://xmlns.jakarta.ee/...

**Additional context**

### PR DESCRIPTION
**Pull request by ivargrimstad**
Signed-off-by: Ivar Grimstad <ivar.grimstad@eclipse-foundation.org>

### CODE REVIEW

**Comment by ivargrimstad** [comment]
Wait with merging this until we have a go from the Platform project. Probably after the call we have on Tuesday, March 24, 2020

**Comment by chrisguindon** [comment]
@ivargrimstad +1 Feel free to create pr as a "Draft" next time when it's not ready!

**Comment by ivargrimstad** [comment]
@chrisguindon This PR is good to go now!

**Comment by chrisguindon** [comment]
Awesome! This is great @ivargrimstad

**Pull request merged**
