### PR TITLE
How to add a reference in Jakarta EE Announcements section from one Jakarta EE Working Group post

### PR DESCRIPTION
**Pull request by cesarhernandezgt**
Solves #1196

### CODE REVIEW

**Review by autumnfound — COMMENTED** [review]
Text LGTM, will look for another +1 from team before merging

**Comment by cesarhernandezgt** [comment]
Hi @karenmcnaughton 

This PR provides the documentation for Keeping Jakarta.ee/news/ in sync with front-page announcements.
@autumnfound already helped with the technical review. As I understand now your review, in terms of the content goal,  is need it.

**Comment by autumnfound** [comment]
@TanjaObradovic Could you take a look at this? I'd like your +1 before merging.

**Comment by TanjaObradovic** [comment]
This looks good to me. I assume it was tested and it works!

**Comment by cesarhernandezgt** [comment]
> This looks good to me. I assume it was tested and it works!

Hi @TanjaObradovic. You are correct, notice that this PR is related to documentation and currently doesn't impact any page from the live website.

**Pull request merged**
