### PR TITLE
Add Webtide testimonial

### PR DESCRIPTION
**Pull request by jmcc0nn3ll**
Contribute here so I can close out https://github.com/jakartaee/collateral/issues/39

### CODE REVIEW

**Comment by aeiras** [comment]
As usual, eres fantastico Jesse!

**Review by autumnfound — APPROVED** [review]
Contribution LGTM, and was able to see it in the preview. Not sure how we want to go about approval for quotes (or if we need it for this?) cc// @TanjaObradovic

**Comment by aeiras** [comment]
Hola Martin, 

The 2 quotes, Primeton's PR is also coming, were approved when the Jelastic quote was also approved. 
We are closing the pilot and adding the guidelines to the website documentation that will welcome WG members to submit their "Why they care about Jakarta". 

Thank you,

**Comment by TanjaObradovic** [comment]
@autumnfound looks great to me!
Thanks @jmcc0nn3ll!

**Pull request merged**
