### PR TITLE
Create blogs section

### LINKED ISSUE #1037: Moving jakartablogs.ee to jakarta.ee
For the website redesign of Jakarta EE, we want to create a blogging platform that will allow users to log in and publish blog posts. The platform must be hosted on blogs.jakarta.ee and ideally allow for moderation.
Timing of this is to correspond with the launch of the revised jakarta.ee website.

### PR DESCRIPTION
**Pull request by ericpoirier**
Signed-off-by: Eric Poirier <eric.poirier@eclipse-foundation.org>

### CODE REVIEW

**Review by autumnfound — APPROVED** [review]
Other than the _yikes_ that is the tracecompass image @ 12mb, this looks good

**Comment by ericpoirier** [comment]
> Other than the _yikes_ that is the tracecompass image @ 12mb, this looks good

All the blogs items are placeholders because I don't have any to test with. the 12mb file will be gone before merging.

**Comment by chrisguindon** [comment]
I am submitting a PR to update hugo-solstice-theme:
https://github.com/jakartaee/jakarta.ee/pull/1353

@ericpoirier this should enable you to finish this PR.

On top of upgrading the theme, I am creating a proxy rule to fixa cors issue that I expect you will have with the jarkatablogs RSS feed. 

When using our new [solstice_rss_blog_list shortcode](https://gitlab.eclipse.org/eclipsefdn/it/webdev/hugo-solstice-theme/-/blob/master/layouts/shortcodes/solstice_rss_blog_list.html), please make sure to use the following URLs: 
You can use /blogs/jakartablogs.xml in the URLs

data-urls="/blogs/jakartablogs.xml,/blogs/index.xml"

Let me know if you have any questions.

**Comment by chrisguindon** [comment]
Converting this PR as a draft since it's still a work in progress.

**Comment by ericpoirier** [comment]
@chrisguindon I updated the blogs section with the new plugin and I'm also using a custom mustache template.

https://deploy-preview-1329--jakartaee.netlify.app/blogs/

**Comment by ericpoirier** [comment]
We have the +1 from Shabnam.

**Review by chrisguindon — APPROVED** [review]

**Pull request merged**
