### PR TITLE
update to Hugo 0.76.5

### PR DESCRIPTION
**Pull request by chrisguindon**
Signed-off-by: Christopher Guindon <chris.guindon@eclipse-foundation.org>

### CODE REVIEW

**Comment by flora8984461** [comment]
Do we want to fix this warning too before merging or create a new issue?

image

**Comment by chrisguindon** [comment]
> Do we want to fix this warning too before merging or create a new issue?
> 
> image

Where is the error coming from?

**Comment by flora8984461** [comment]
> > Do we want to fix this warning too before merging or create a new issue?
> > image
> 
> Where is the warning coming from? It would be best to fix it now if we can

This is confusing, the warning does not tell me where the cause is.
I have checked all the `isset ` we are calling, while I don't think anything is wrong here. They all match the syntax:
isset COLLECTION INDEX / isset COLLECTION KEY  🤔

**Review by flora8984461 — APPROVED** [review]
lgtm

**Pull request merged**
