### PR TITLE
Embedded membership form on jakarta.ee

### LINKED ISSUE #1328: Embed membership form on jakarta.ee
Similar to https://github.com/EclipseFdn/iot.eclipse.org/issues/666, we would like to embed the contact us form on jakarta.ee.

Here is the code to embed the form:
```
<!--[if lte IE 8]>
<script charset="utf-8" type="text/javascript" src="//js.hsforms.net/forms/v2-legacy.js"></script>
<![endif]-->
<script charset="utf-8" type="text/javascript" src="//js.hsforms.net/forms/v2.js"></script>
<script>
  hbspt.forms.create({
	region: "na1",
	portalId: "5413615",
	formId: "92df565f-cf45-49dc-8f2d-f59ebe148d13"
});
</script>
```

CC @shabnammayel

### PR DESCRIPTION
**Pull request by linkfang**
Fixes [issue1328](https://github.com/jakartaee/jakarta.ee/issues/1328)

### CODE REVIEW

**Review by autumnfound — APPROVED** [review]

**Comment by linkfang** [comment]
Got +1 from both Shanda and Shabnam

**Comment by ericpoirier** [comment]
@linkfang can you rebase your PR locally?

**Comment by linkfang** [comment]
> @linkfang can you rebase your PR locally?

Sure, done!

**Comment by linkfang** [comment]
Wait a sec, need to update an URL in the changes got from src branch.

From "https://accounts.eclipse.org/contact/membership/jakarta-ee" to "/membership/join-us" (/membership->index.html)

**Comment by linkfang** [comment]
Done, ready for review

**Review by ericpoirier — APPROVED** [review]

**Pull request merged**
