### PR TITLE
Remove listing of subpage

### PR DESCRIPTION
**Pull request by ivargrimstad**
Signed-off-by: Ivar Grimstad <ivar.grimstad@eclipse-foundation.org>

### CODE REVIEW

**Comment by TanjaObradovic** [comment]
+1 thanks @ivargrimstad

**Comment by ivargrimstad** [comment]
I think this probably should be done another way... The link to the subpage does not seem to work this way. @chrisguindon Any tips?

**Comment by chrisguindon** [comment]
I think this is causing https://deploy-preview-695--jakartaee.netlify.com/connect/mailing-lists/ to return a 404.

@ivargrimstad  you could rename the file back to _index.md but add the following metadata to the page:

layout: "single"

As we are doing here https://raw.githubusercontent.com/jakartaee/jakarta.ee/src/content/compatibility/_index.md

**Comment by ivargrimstad** [comment]
> I think this is causing https://deploy-preview-695--jakartaee.netlify.com/connect/mailing-lists/ to return a 404.
> 
> @ivargrimstad you could rename the file back to _index.md but add the following metadata to the page:
> 
> layout: "single"
> 
> As we are doing here https://raw.githubusercontent.com/jakartaee/jakarta.ee/src/content/compatibility/_index.md

Thanks @chrisguindon! That did the trick :)

**Comment by chrisguindon** [comment]
Great! Thanks @ivargrimstad

**Pull request merged**
