### PR TITLE
Add GSJUG as a Jakarta NoSQL adopter

### PR DESCRIPTION
**Pull request by mpredli01**
Signed-off-by: Michael P. Redlich <mike@redlich.net>

### CODE REVIEW

**Comment by autumnfound** [comment]
It doesn't look like you included the adopters file update in the PR?

**Comment by autumnfound** [comment]
you should be able to just submit a patch to a branch to update a PR, there is no need to create a new PR for changes

**Comment by mpredli01** [comment]
Hi @autumnfound:

I just updated pushed "adding-gsjug" branch. Hopefully, this will work!

Mike.

**Review by autumnfound — APPROVED** [review]

**Comment by autumnfound** [comment]
> Hi @autumnfound:
> 
> I just updated pushed "adding-gsjug" branch. Hopefully, this will work!
> 
> Mike.

LGTM! Just want a +1 from Ivar since he was working with this before. I was just helping unblock :)

**Review by ivargrimstad — APPROVED** [review]

**Pull request merged**
