### PR TITLE
update package.json

### PR DESCRIPTION
**Pull request by ericpoirier**
Signed-off-by: Eric Poirier <eric.poirier@eclipse-foundation.org>

### CODE REVIEW

**Comment by autumnfound** [comment]
Side content text is not accessible with new/updated side content background colour. We should either add a var to set the side background colour back to what it was originally, or make the text black to be legible.

**Comment by chrisguindon** [comment]
@ericpoirier How about you close https://github.com/jakartaee/jakarta.ee/pull/790 and bring those changes here.

Make sure to generate a fresh package-lock.json file.

**Comment by ericpoirier** [comment]
> Side content text is not accessible with new/updated side content background colour. We should either add a var to set the side background colour back to what it was originally, or make the text black to be legible.

Not sure what backgroud colour you refer to here. Can you tell me which page you would like to change the background?

**Comment by ericpoirier** [comment]
>     * lock file is missing
Done
>     * the Duke "ad" text is now white and the background is lighter than it should!
 I added the changes to the Duke's award PR here in this PR.

**Pull request merged**
