### PR TITLE
Updated members list to use REM API

### PR DESCRIPTION
**Pull request by linkfang**
Signed-off-by: Zhou Fang <zhou.fang@eclipse-foundation.org>

### CODE REVIEW

**Comment by linkfang** [comment]
Hi @TanjaObradovic , @shabnammayel ,

For all our working groups' member list, we are switching to use our API to display them.  The main benefit is that we don't need to manually update our website and the logos will always be up-to-date, plus, our members can manage it by themselves via our Member Portal website. 

For Jakarta EE, there are 2 small visual changes.
1. The member list on home page, we decided to remove the carousel to make sure all members will be listed/seen without any further operation from users.
2. Some of the members' logos are slightly different from the ones on prod as they uploaded different ones to Eclipse.org.

Let me know if everything looks good and works for you, thanks!

https://deploy-preview-1458--jakartaee.netlify.app/
https://deploy-preview-1458--jakartaee.netlify.app/membership/members/

**Comment by linkfang** [comment]
Hi @TanjaObradovic ,  @shabnammayel , just would like to confirm if this is still on your radar, thanks!

**Comment by shabnammayel** [comment]
LGTM! Thanks @linkfang

**Review by autumnfound — APPROVED** [review]

**Review by ericpoirier — APPROVED** [review]

**Comment by linkfang** [comment]
Found a small CSS issue for the headers in mobile view and fixed it, can you take another look? Thanks!

**Pull request merged**
