### PR TITLE
Update Footer To Use Absolute Paths For Images

### PR DESCRIPTION
**Pull request by yashTEF**
Changes relative paths in footer for images to absolute, for fragment/template usage.

### CODE REVIEW

**Comment by yashTEF** [comment]
@autumnfound , Could you review this? 

So eclipse-ee4j/starter#293 can be closed.

**Comment by autumnfound** [comment]
@oliviergoulet5 if we want to use absolute URLs, the Hugo equivalent is `{{ absURL "/images/jakarta/jakarta-ee-logo-white.svg" }}`, correct? It's been a little while so I'm rusty and I want to confirm.

@yashTEF once I confirm the syntax, we should switch to this. We use preview links that allow us to have previews of functionality, so hard-coding the production host could lead to errors in previews if the assets ever change.

**Comment by oliviergoulet5** [comment]
@autumnfound That's correct

**Comment by yashTEF** [comment]
> @yashTEF once I confirm the syntax, we should switch to this. We use preview links that allow us to have previews of functionality, so hard-coding the production host could lead to errors in previews if the assets ever change.

Yes, I was confused too when I saw how urls were being referenced in the header/navbar.

Will change to this.

**Review by autumnfound — APPROVED** [review]

**Pull request merged**
