### PR TITLE
Updated Pivotal to VMWare

### LINKED ISSUE #1317: Updating https://jakarta.ee/membership/members/ (Pivotal -> VMWare)
Can we update logo of Pivotal to VMWare? This acquisition happened awhile ago, so we need to correct it? I am hoping you have the VMWare logo already, but let me know if need help with it.

### PR DESCRIPTION
**Pull request by linkfang**
Fixes [issue1317](https://github.com/jakartaee/jakarta.ee/issues/1317)

### CODE REVIEW

**Comment by linkfang** [comment]
Got +1 from Tanja

**Comment by autumnfound** [comment]
If the pivotal logo is no longer used, we should remove it

**Comment by linkfang** [comment]
> If the pivotal logo is no longer used, we should remove it

Yep, I did remove it (jakarta-member_pivotal.svg)

**Review by autumnfound — APPROVED** [review]

**Comment by autumnfound** [comment]
D'oh. Early Friday brain kicking in, merged haha

**Pull request merged**
