### PR TITLE
update community china brief, update jakartaone event

### PR DESCRIPTION
**Pull request by laliwa**

### CODE REVIEW

**Comment by autumnfound** [comment]
Are the images on the Community -> China page social media share banners or just in page promotion of the event? If those banners are meant just for this page, we should convert them to jpg as that would likely cut the file size in half with negligible quality loss.

**Comment by laliwa** [comment]
> Are the images on the Community -> China page social media share banners or just in page promotion of the event? If those banners are meant just for this page, we should convert them to jpg as that would likely cut the file size in half with negligible quality loss.

As the event is concluded, don't need the pic(originally for promoting) anymore, so maybe we should go on with the new changes.

**Comment by laliwa** [comment]
> Are the images on the Community -> China page social media share banners or just in page promotion of the event? If those banners are meant just for this page, we should convert them to jpg as that would likely cut the file size in half with negligible quality loss.

As the event is concluded, don't need the pic(originally for promoting) anymore, so maybe we should go on with the new changes.

**Comment by ericpoirier** [comment]
@laliwa this PR also needs to be rebased. Let me know when it is ready to be merged and I can help.

**Comment by laliwa** [comment]
> @laliwa this PR also needs to be rebased. Let me know when it is ready to be merged and I can help.

@ericpoirier sorry I am not sure what you mean by "it is ready to be merged", do I need to check some code or sth? pls, guide me. And also tell me what I should do to avoid rebase next time, so I will not put an unnecessary workload on you.

**Comment by ericpoirier** [comment]
> > @laliwa this PR also needs to be rebased. Let me know when it is ready to be merged and I can help.
> 
> @ericpoirier sorry I am not sure what you mean by "it is ready to be merged", do I need to check some code or sth? pls, guide me. And also tell me what I should do to avoid rebase next time, so I will not put an unnecessary workload on you.

I was asking because there was still back and forth with @autumnfound but I can help rebase this PR and merge if you think it's ready to be merged to production.

**Comment by autumnfound** [comment]
RE the images, its a small nitpick and it shouldn't block us from going live with this! It can serve as a note for next time to optimize images.

**Comment by laliwa** [comment]
> > > @laliwa this PR also needs to be rebased. Let me know when it is ready to be merged and I can help.
> > 
> > 
> > @ericpoirier sorry I am not sure what you mean by "it is ready to be merged", do I need to check some code or sth? pls, guide me. And also tell me what I should do to avoid rebase next time, so I will not put an unnecessary workload on you.
> 
> I was asking because there was still back and forth with @autumnfound but I can help rebase this PR and merge if you think it's ready to be merged to production.

I see, I think it is OK to merge.

**Review by ericpoirier — APPROVED** [review]

**Pull request merged**
