### PR TITLE
Change side bar

### LINKED ISSUE #2044: Change Sidebar on Specification Pages
On the current specification pages there is an "Adopt a Spec" graphic in the sidebar:

image

Can we please replace the the text "Adopt a Spec" with "Learn Jakarta EE" and add some text under it, "Find Starter Guides, Tutorials, and Documentation to help you get started with Jakarta EE."

Then change the learn more link to direct to the learn page: https://jakarta.ee/learn/

It should look like this:

image

### PR DESCRIPTION
**Pull request by InocencioC**
Resolves #2044

### CODE REVIEW

**Comment by oliviergoulet5** [comment]
@InocencioC Preview builds get triggered each time you push. You can share the URL from the netlify bot's comment:

image

**Comment by InocencioC** [comment]
Thanks for the explanation, that makes sense now! I'll make sure to check the bot's comment for the preview URL after each push. By the way, does the preview URL expire after some time, or is it always accessible ?

@oliviergoulet5

**Comment by oliviergoulet5** [comment]
No problem! And yes, they are always accessible! Or at least, they last longer than anybody would ever need.

**Review by oliviergoulet5 — APPROVED** [review]

**Comment by oliviergoulet5** [comment]
Great work! Thanks for your contribution @InocencioC!

**Pull request merged**
