### PR TITLE
Tabular view of the Jakarta EE committees meeting minutes per year #726

### PR DESCRIPTION
**Pull request by autumnfound**
Signed-off-by: Martin Lowe <martin.lowe@eclipse-foundation.org>

### CODE REVIEW

**Comment by autumnfound** [comment]
Pulled to draft as it was pointed out that this isn't in tabs, d'oh!

**Comment by autumnfound** [comment]
Making changes to the general meeting minutes tab would likely require some design work. Right now, we are separating the meeting minutes on the committee pages by year tabs. On the general page, it is done by committee. 

In terms of design, tabs in tabs aren't necessarily ideal imo, but could likely be done. Having a situation like a nested table header would not be suitable long-term as it would be incredibly busy and could very easily spill into extra rows creating a messy looking interface. One way to get around this is to break out the tabs into multiple tabbed sections with a heading+anchor so that the old links would still bring users to the correct section.

Additionally this would have to be done in the base theme, as that's where this functionality lives.

**Comment by chrisguindon** [comment]
@autumnfound I would like to see the meeting minutes in the .tab-content div organized by year.

**Comment by chrisguindon** [comment]
I agree that tabs are not ideal! 

We should keep them on https://deploy-preview-742--jakartaee.netlify.app/meeting_minutes/ for each committee but we could drop them here: https://deploy-preview-742--jakartaee.netlify.app/committees/steering/ in favor to what I am describing in my previous comment?

**Pull request merged**
