### PR TITLE
Add the Jakarta Bean Validation schema files to the website

### PR DESCRIPTION
**Pull request by starksm64**
Signed-off-by: Scott M Stark <starksm64@gmail.com>

### CODE REVIEW

**Comment by ivargrimstad** [comment]
@chrisguindon It seems like the travis build is stuck (or at least doesn't report back status). Also applies to other PRs in this repository.

**Comment by chrisguindon** [comment]
@ivargrimstad do you have access to restart the travis-ci build as a committer on this repo?

**Comment by ivargrimstad** [comment]
@chrisguindon No, there is no "Restart build" button showing

**Comment by chrisguindon** [comment]
Are you logged in to travis-ci? 

The button should only be available to folks with write access to the repository.

**Comment by ivargrimstad** [comment]
Yes, but let's take this discussion off this issue. I'll slack you :)

**Pull request merged**
