### PR TITLE
Add Blog Post on javax to jakartaee namespace change progress

### PR DESCRIPTION
**Pull request by karianna**

### CODE REVIEW

**Comment by karianna** [comment]
New post not appearing in blogs list, not sure why.

**Comment by jgallimore** [comment]
@karianna Would the date here: https://github.com/jakartaee/jakarta.ee/pull/1514/files#diff-b9a9cf58d1495d55269c95030e40ef69490e70614d9b9a9acfb903710db786acR3 effectively embargo it?

**Comment by karianna** [comment]
I can make the date today if folks prefer, was just giving some time for review.

**Comment by karianna** [comment]
Ah, I wonder if that's why the post didn't show...

**Comment by ivargrimstad** [comment]
Yes @karianna, the date is the publish date, so it won't show up in the preview either until after that date...

**Comment by karianna** [comment]
OK that looks good now - I'd say this is ready to merge with @ivargrimstad approval as a EF representative.

**Comment by chrisguindon** [comment]
I am noticing that this blog post is including HTML for tables. However, the site is not configured to render HTML in markdown files: 

It would be best to format tables using the markdown syntax:
https://www.markdownguide.org/extended-syntax/#tables

See: https://jakarta.ee/blogs/javax-jakartaee-namespace-ecosystem-progress/

**Comment by karianna** [comment]
Fixed in https://github.com/jakartaee/jakarta.ee/pull/1520 - @Ivar Grimstad
***@***.***> are you able to merge?

Cheers,
Martijn

**Comment by chrisguindon** [comment]
Thanks @karianna

**Comment by TanjaObradovic** [comment]
great! thx all!!

**Pull request merged**
