### PR TITLE
jakarta 9.1 contributors list data

### PR DESCRIPTION
**Pull request by Dexmaster**
related issue #1159

- updated sh file now you can provide 3 optional arguments, file name, from_date and to_date
- generated jakarta-ee-9.1.json with 22 authors of merged prs and commits on jakartaee/specifications

P.S. dates used are between 2020-11-21 and 2021-05-18 (so number of authors might increase as to_date is in future)

Signed-off-by: Andrii Malytskyi <amalytskyi@tomitribe.com>

### CODE REVIEW

**Comment by Dexmaster** [comment]
If someone wants to try this tool you can run command 
```bash
GH_TOKEN=<token> npm run generate_contributor_list
#or with arguments of your choice
GH_TOKEN=<token> npm run generate_contributor_list -- jakarta-ee-9.1.json 2020-11-21 2021-05-18
```

**Comment by aeiras** [comment]
Great work Andrii! Thank you.

**Review by cesarhernandezgt — APPROVED** [review]

**Comment by cesarhernandezgt** [comment]
Thank you @Dexmaster for rebasing with the latest master(src).
cc: @chrisguindon @autumnfound this PR is now green and ready for review.

**Comment by chrisguindon** [comment]
Thanks @cesarhernandezgt @Dexmaster

**Pull request merged**
