### PR TITLE
Adding JUGs logos on the "Adopt a Spec" page #669

### PR DESCRIPTION
**Pull request by autumnfound**
Signed-off-by: Martin Lowe <martin.lowe@eclipse-foundation.org>

### CODE REVIEW

**Comment by chrisguindon** [comment]
Hi @shabnammayel,
What do you think of this? https://deploy-preview-671--jakartaee.netlify.com/community/adopt-a-spec/

**Comment by autumnfound** [comment]
> can we please make the logo smaller? and also add the Madras JUG logo? thanks

@shabnammayel Madras was missing as it wasn't live at the time I wrote this code. It'll be there when we merge it in. I can make the logos smaller, how much smaller were you thinking? Half the size?

**Comment by TanjaObradovic** [comment]
I'm not Shabnam, but let's try with half the size. I think that would be good. @shabnammayel can confirm.

**Comment by chrisguindon** [comment]
Hi @shabnammayel / @TanjaObradovic 

What do you think of this? https://deploy-preview-671--jakartaee.netlify.com/community/adopt-a-spec/

**Comment by TanjaObradovic** [comment]
+1 from me!

**Pull request merged**
