### PR TITLE
Add InforSuite 8 platform

### LINKED ISSUE #1071: Please add InforSuite Application Server as Compatible product of Jakarta EE Full Platform
To include your Compatible Software Product on the Jakarta EE official list of Compatible Software Products, please provide the following information:

**The URL to the Eclipse Foundation profile to confirm that you are an authorized representative of the company whose product information you are submitting**
https://www.eclipse.org/membership/showMember.php?member_id=1487

**A product name and version**
InforSuite Application Server V10

**The Profile (Full Platform, Web Profile, Both) that the Compatible Product is submitted to be listed under**

**A ZIP file with a product logo with a transparent background in SVG format (optional)**
https://github.com/codff/InforSuite/archive/main.zip

**The Participant, Enterprise or Strategic Member name supporting the Compatible Software Product**
Shandong Cvicse Middleware Co.,Ltd.

**The URL to the approved certification issue demonstrating compatibility as defined in the Jakarta EE TCK Process**
Full Platform:https://github.com/eclipse-ee4j/jakartaee-platform/issues/306

**The URL where Compatible Software Product is available for download**
http://www.inforbus.com/as.html

### PR DESCRIPTION
**Pull request by flora8984461**
Fix #1071 

Signed-off-by: Yi Liu <yi.liu@eclipse-foundation.org>

### CODE REVIEW

**Review by autumnfound — APPROVED** [review]

**Comment by chrisguindon** [comment]
@TanjaObradovic are we good to add  InforSuite: https://deploy-preview-1073--jakartaee.netlify.app/compatibility/#tab-one

**Review by ivargrimstad — COMMENTED** [review]
Wait until https://github.com/eclipse-ee4j/jakartaee-platform/issues/306 has been approved and the `accepted' label added by the platform team.

**Comment by chrisguindon** [comment]
Thanks @ivargrimstad 

We will wait for your +1!

**Comment by chrisguindon** [comment]
I am going to start using this new `waiting approval` label for PR that are approved by webdev but waiting approval from an accountable team/person.

I am open to renaming this label if someone suggests something better.

@autumnfound @ericpoirier,

as a side note, we should look for a +1 from the EF Program Manager (@TanjaObradovic) when updating the compatible product page! 

The webdev team can validate the code that was submitted but we don't have the expertise to validate if the product is ready to go on the website.

**Comment by TanjaObradovic** [comment]
+1 from me.

**Pull request merged**
