### PR TITLE
#1087 Add case studies section to resources

### LINKED ISSUE #1087: Add case studies section to jakarta.ee/resources/
Please create a heading for Case Studies on the Jakarta EE Resources page. Attached is the Payara member case study to go under this section

Content:
### Case Studies
[Payara Services Gains an Equal Footing With Industry Leaders at the Eclipse Foundation
](https://outreach.eclipse.foundation/payara-services-open-source-case-study)

### PR DESCRIPTION
**Pull request by flora8984461**
Fix #1087 

Hi Eric @laliwa Can you help me with the translation? Thanks!

the words included: 

"Case Studies"
and
"Payara Services Gains an Equal Footing With Industry Leaders at the Eclipse Foundation"

Signed-off-by: Yi Liu <yi.liu@eclipse-foundation.org>

### CODE REVIEW

**Comment by laliwa** [comment]
> Fix #1087
> 
> Hi Eric @laliwa Can you help me with the translation? Thanks!
> 
> the words included:
> 
> "Case Studies"
> and
> "Payara Services Gains an Equal Footing With Industry Leaders at the Eclipse Foundation"
> 
> Signed-off-by: Yi Liu [yi.liu@eclipse-foundation.org](mailto:yi.liu@eclipse-foundation.org)

I will suggest this:
Case Studies
案例
Payara Services Gains an Equal Footing With Industry Leaders at the Eclipse Foundation
了解Payara Services如何在Eclipse Foundation获得了与行业领导者同等的地位

You can also just committed this and after it has been merged, I will commit my translation version, too. 
And since the case study is so important to attract more people to join the working group, I suggest that we put the case study item on top of the resource.  
Even we could put it right after the introduction section of the working group on the about page.
Personal views , for reference only.

**Comment by flora8984461** [comment]
> > Fix #1087
> > Hi Eric @laliwa Can you help me with the translation? Thanks!
> > the words included:
> > "Case Studies"
> > and
> > "Payara Services Gains an Equal Footing With Industry Leaders at the Eclipse Foundation"
> > Signed-off-by: Yi Liu [yi.liu@eclipse-foundation.org](mailto:yi.liu@eclipse-foundation.org)
> 
> I will suggest this:
> Case Studies
> 案例
> Payara Services Gains an Equal Footing With Industry Leaders at the Eclipse Foundation
> 了解Payara Services如何在Eclipse Foundation获得了与行业领导者同等的地位
> 
> You can also just committed this and after it has been merged, I will commit my translation version, too.
> And since the case study is so important to attract more people to join the working group, I suggest that we put the case study item on top of the resource.
> Even we could put it right after the introduction section of the working group on the about page.
> Personal views , for reference only.

Thanks for the translation and valuable advice! I can add the translation within this PR since it's not too much. Just wanna confirm with @jph152 about the position of the case studies.

Hi @jph152 Eric made some suggestions about where to put "Case Studies", does it sound good to you to put "Case Studies" on top of the resource (Like before "Documentation")?  Or put it right after the introduction section of the working group on the about page?

Thanks!

**Comment by jph152** [comment]
+1 Let's put it at the top of the Resources page. Once we have more member case studies for Jakarta EE published, we can look into putting them on the about page. Thanks!

**Comment by aeiras** [comment]
Hola Eric, your feedback is spot on on this ticket. 

Chris, I would like to add a feature that could increase the scalability of the Resources Tab.  How about we find a way to make a few of the items listed have its own pages? Like that it would be easier to share those pages, refer to them, tweet them, etc. The benefits are endless.

**Comment by chrisguindon** [comment]
@aeiras Could this be something we can address with the website re-design project? https://github.com/jakartaee/jakarta.ee/issues/1070

**Comment by aeiras** [comment]
Yes, Chris! that would be wonderful if we could add it there in that list or keep it in mind when implementing the extra features. 
Thats why I used the "feature" nice to have wish after placement, which is most important. First, it must show up, then improvements are just fun!

**Pull request merged**
