### PR TITLE
Add Madras JUG to JSON-P adopters

### PR DESCRIPTION
**Pull request by ivargrimstad**
Signed-off-by: Ivar Grimstad <ivar.grimstad@eclipse-foundation.org>

### CODE REVIEW

**Comment by TanjaObradovic** [comment]
Any chance to make these logo's smaller as well? half the size?

**Comment by chrisguindon** [comment]
@TanjaObradovic The change was already merged, can you make this request on https://github.com/jakartaee/jakarta.ee/issues/669 as this is still a work and progress and it's related to the adopt-a-spec!

**Comment by zarub2k** [comment]
@TanjaObradovic Where can I see the logo?

**Comment by TanjaObradovic** [comment]
@zarub2k You can see the logo at 2 places
_Adopt-a-Spec link_
https://jakarta.ee/community/adopt-a-spec/
_Jakarta JSON Processing Specification link_
https://jakarta.ee/specifications/jsonp/

**Pull request merged**
